#!/bin/bash

title=$*

[ -z "$title" ] && echo "Please enter a title" && exit 1

slug=$(sed -e 's/[^a-z]\+/-/g' -e 's/-$//' <<< ${title,,})
date=$(date +%F)

vim "+normal i---title: $titleslug: $slugdate: $datetags: draft: true---" \
    "$BLOG_DIR/src/posts/$date-$slug.md"
